services:
  - type: web
    name: estoque-freezer-hotel
    runtime: python
    buildCommand: pip install --default-timeout=100 -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: EMAIL_DESTINO
        value: mwfreitas@gmail.com
      - key: DATABASE_URL
        sync: false
